name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        rust-version: [stable, nightly]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}

    - name: Build and test
      run: |
        cargo build --verbose
        cargo test --verbose
