name: Rust CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: macos-latest
        strategy:
            matrix:
                rust-version: [stable]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Rust ${{ matrix.rust-version }}
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.rust-version }}

            - name: Test rust code
              run: cargo test
              working-directory: ./arkham_tcg_rust
